package com.example.mybatisdemo.mapper;

import com.example.mybatisdemo.pojo.CommonTask;
import com.example.mybatisdemo.pojo.CommonTaskExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;


@Component
@Mapper
public interface CommonTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int countByExample(CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int deleteByExample(CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int insert(CommonTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int insertSelective(CommonTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    List<CommonTask> selectByExample(CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    CommonTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommonTask record, @Param("example") CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommonTask record, @Param("example") CommonTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommonTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommonTask record);

    /**
     * 用于定时任务扫表，判断是否有待执行的任务因为pod宕机，没有及时更新状态
     * 不要为了偷懒，直接返回一行的所有数据，即select *
     * @param status 任务状态
     * @return 返回查询到的数据
     */
    List<CommonTask> getTaskByPendingStatus(@Param("status") Short status);

    /**
     * 判断任务到期 任务状态是否得到更新
     * @param busId 任务id
     * @return 返回信息
     */
    CommonTask getDelayTaskByBusId(@Param("busId") Long busId);
}